# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=32, verbose_name='Apellidos')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('calle', models.CharField(blank=True, max_length=32, null=True, verbose_name='Calle')),
                ('poblacion', models.CharField(blank=True, max_length=16, null=True, verbose_name='Poblacion')),
                ('codigo_postal', models.CharField(blank=True, max_length=8, null=True, verbose_name='Codigo Postal')),
                ('pais', models.CharField(max_length=32, verbose_name='Pais')),
                ('email', models.EmailField(max_length=32, unique=True, verbose_name='E-Mail')),
                ('sitio_web', models.URLField(blank=True, max_length=32, null=True, verbose_name='Sitio Web')),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
